[package]
name = "libktx-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libktx-rs-sys = { path = "../libktx-rs-sys", version = "0.1.0" }
derive_builder = "^0.10"